# Generated by Django 3.0.8 on 2020-07-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logestics', '0002_order_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
